### ISSUE TITLE
Looking for help with an i18n strategy

### ISSUE THREAD

**Issue by joe-mohan** [johannschopplich/nuxt-prepare#12]
### Describe the feature

Sorry not a feature request. 

For sites with i18n in nuxt2 we would pass a global object to each route in the generate script. The global payload needs to match the locale of each page so we would get every locale, loop through them to get the correct global payloads and then pass them in:

```
return {
      route: path,
      globals: globals[locale],
    }
```

With nuxt-prepare, whats the best strategy for this scenario? 
Following the [pinia example](https://github.com/johannschopplich/nuxt-prepare/blob/main/playground/store.prepare.ts), and imagining the todos api had i18n - would you get all of the todos in every locale at this stage and then pass them all to the store? 

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-prepare/issues).

**Comment by johannschopplich** [comment]
Hi there,

I don't quite understand your use case, but you have several options: Use `useAsyncData` on a specific route to have the payload stored there. Only what you return inside the `useAsyncData` callback will be saved per route.

Or, sticking with Nuxt Prepare, export multiple entries in your prepare script: For example, don't export globals (because the import will bundle the whole item), but split the data in your prepare script to allow individual imports like:

```ts
// `server.prepare.ts`
import { defineNuxtPrepareHandler } from 'nuxt-prepare/config'

export default defineNuxtPrepareHandler(async () => {
  return {
    state: {
      enData,
      deData,
      // etc.
    }
  }
})
```

And import it where needed:

```ts
import { enData } from "#nuxt-prepare"
```

Hope that helps!

**Comment by joe-mohan** [comment]
Thanks, makes sense. 

Use case is to be able to generate a fully static site and use a shared global payload in all pages. But that global is i18n so potentially quite large. I assume its not a good idea to just have that entire payload sitting there and switch the locale based on the route?  
So for us, grabbing everything in useAsyncData is the best way to go I think as it'll make it easier when generating the static site.
